trigger:
- main-v16

pool:
  vmImage: 'windows-latest'

variables:
  projectName: 'Umbraco.Cms.Integrations.Crm.Hubspot'
  project: 'src/$(projectName)/$(projectName).csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: DotNetCoreCLI@2
  displayName: 'NuGet Restore'
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    projects: '$(project)'
    includeNuGetOrg: true

- task: UseDotNet@2
  displayName: 'Use SDK version 9.0.203'
  inputs:
    packageType: 'sdk'
    version: '9.0.203'

- task: VSBuild@1
  displayName: 'Build Project'
  inputs:
    solution: '$(project)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Create NuGet Package'
  inputs:
    command: 'pack'
    arguments: '--configuration $(buildConfiguration)'
    packagesToPack: '$(project)'
    versioningScheme: 'off'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
