name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
  nodeVersion: 18.x
  solution: src/Umbraco.Cms.Integrations.Search.Algolia/Umbraco.Cms.Integrations.Search.Algolia.csproj
  buildConfiguration: Release
  DOTNET_NOLOGO: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  productGroup: 'DXP'
  productName: 'Umbraco.Cms.Integrations.Search.Algolia'
  productVersion: '2.3.2'
  DT_API_KEY: $(dtApiKey)
  DT_BASE_URL: 'https://ca-live-global-dtrack-api.purplemoss-6e7d841c.westeurope.azurecontainerapps.io/api/v1/bom'

stages: 
  - stage: Build
    variables:
      NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
      npm_config_cache: $(Pipeline.Workspace)/.npm_client
    jobs:
      - job: Build
        pool: 
          vmImage: ubuntu-latest
        steps:
          # Checkout source (avoid shallow clone to calculate version height)
          - checkout: self
            fetchDepth: 0

          # Setup build environment
          - task: NuGetAuthenticate@1
            displayName: Authenticate NuGet

          # Cache and restore NuGet packages
          - task: Cache@2
            condition: ${{ parameters.cache_nuget }}
            displayName: Cache NuGet packages
            inputs:
              key: 'nuget | "$(Agent.OS)" | **/packages.lock.json, !**/bin/**, !**/obj/**'
              restoreKeys: |
                nuget | "$(Agent.OS)"
                nuget
              path: $(NUGET_PACKAGES)

          - script: dotnet restore $(solution) --locked-mode
            displayName: Restore NuGet packages

          # Build
          - script: dotnet build $(solution) --configuration $(buildConfiguration) --no-restore -p:ContinuousIntegrationBuild=true
            displayName: Run dotnet build

          # Pack
          - script: dotnet pack $(solution) --configuration $(buildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory)/nupkg
            displayName: Run dotnet pack

          # Publish
          - task: PublishPipelineArtifact@1
            displayName: Publish NuGet packages
            inputs:
              targetPath: $(Build.ArtifactStagingDirectory)/nupkg
              artifactName: nupkg

          - task: PublishPipelineArtifact@1
            displayName: Publish build output
            inputs:
              targetPath: $(Build.SourcesDirectory)
              artifactName: build_output

          # Generate/upload SBOM with cdxgen
          - script: |
              cd $(Build.SourcesDirectory)
              npm install --global @cyclonedx/cdxgen
            displayName: 'Install cdxgen'

          - script: |
              mkdir -p $(Build.ArtifactStagingDirectory)/bom
              cd $(Build.SourcesDirectory)

              cdxgen --recurse \
              --output $(Build.ArtifactStagingDirectory)/bom/bom.json \
              --json-pretty \
              --project-group "$(productGroup)" \
              --project-name "$(productName)" \
              --project-version "$(productVersion)" \
              --server-url "$(DT_BASE_URL)" \
              --api-key "$(DT_API_KEY)"
            displayName: 'Generate & Upload SBOM with cdxgen'
            env:
              DT_API_KEY: $(DT_API_KEY)
              DT_BASE_URL: $(DT_BASE_URL)

          # Publish SBOM artifact
          - task: PublishPipelineArtifact@1
            displayName: 'Publish SBOM Artifact'
            inputs:
              targetPath: $(Build.ArtifactStagingDirectory)/bom
              artifactName: SBOM
