trigger:
- feature/SEMRUSH

pool:
  vmImage: 'windows-latest'

variables:
  projectName: 'Umbraco.Cms.Integrations.SEO.SemrushTools'
  project: 'src/$(projectName)/$(projectName).csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: VSBuild@1
  displayName: 'Build Project'
  inputs:
    solution: '$(project)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CmdLine@2
  displayName: 'Create Umbraco Package'
  inputs:
    script: |
      dotnet tool install --global Umbraco.Tools.Packages
      cd src/$(projectName)/
      umbpack pack .\package.xml -o $(Build.ArtifactStagingDirectory)
      cd ../../

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'