<Project Sdk="Microsoft.NET.Sdk.Razor">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
		<EnableDefaultContentItems>false</EnableDefaultContentItems>
		<StaticWebAssetBasePath>/App_Plugins/Semrush</StaticWebAssetBasePath>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>Umbraco.Cms.Integrations.SEO.Semrush</PackageId>
		<Title>Umbraco CMS Integrations: SEO - Semrush</Title>
		<Description>An extension for Umbraco CMS providing keyword research tools powered by Semrush via a content app.</Description>
		<PackageIconUrl></PackageIconUrl>
		<PackageProjectUrl>https://github.com/umbraco/Umbraco.Cms.Integrations/blob/main-v18/src/Umbraco.Cms.Integrations.SEO.Semrush</PackageProjectUrl>
		<RepositoryUrl>https://github.com/umbraco/Umbraco.Cms.Integrations</RepositoryUrl>
		<Authors>Umbraco HQ</Authors>
		<Company>Umbraco</Company>
		<PackageTags>Umbraco;Umbraco-Marketplace</PackageTags>
		<PackageIcon>semrush.png</PackageIcon>
		<PackageReadmeFile>readme.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Umbraco.Cms.Api.Common" />
		<PackageReference Include="Umbraco.Cms.Api.Management" />
		<PackageReference Include="Umbraco.Cms.Web.Common" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="semrush.png">
			<Pack>true</Pack>
			<PackagePath>\</PackagePath>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<None Include="docs\readme.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="wwwroot\**\*" Pack="true" PackagePath="staticwebassets\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Views\**" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="EmbeddedResources\semrushColumns.json" />
	  <EmbeddedResource Include="EmbeddedResources\semrushDataSources.json" />
	</ItemGroup>
</Project>
