<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
	  <Nullable>enable</Nullable>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
	  <EnableDefaultContentItems>false</EnableDefaultContentItems>
	  <StaticWebAssetBasePath>/App_Plugins/Dynamics</StaticWebAssetBasePath>
	  <CompressionEnabled>false</CompressionEnabled>
  </PropertyGroup>

	<PropertyGroup>
		<PackageId>Umbraco.Cms.Integrations.Crm.Dynamics</PackageId>
		<Title>Umbraco CMS Integrations: CRM - Dynamics</Title>
		<Description>An extension for Umbraco CMS providing a form picker and rendering component for Dynamics 365 Marketing.</Description>
		<PackageIconUrl></PackageIconUrl>
		<PackageProjectUrl>https://github.com/umbraco/Umbraco.Cms.Integrations/blob/main-v17/src/Umbraco.Cms.Integrations.Crm.Dynamics</PackageProjectUrl>
		<RepositoryUrl>https://github.com/umbraco/Umbraco.Cms.Integrations</RepositoryUrl>
		<Authors>Umbraco HQ</Authors>
		<Company>Umbraco</Company>
		<PackageTags>Umbraco;Umbraco-Marketplace</PackageTags>
		<PackageIcon>dynamics.png</PackageIcon>
		<PackageReadmeFile>readme.md</PackageReadmeFile>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="Umbraco.Cms.Api.Common" />
		<PackageReference Include="Umbraco.Cms.Api.Management" />
		<PackageReference Include="Umbraco.Cms.Web.Common" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="dynamics.png">
			<Pack>true</Pack>
			<PackagePath>\</PackagePath>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<None Include="docs\readme.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="wwwroot\**\*" Pack="true" PackagePath="staticwebassets\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Views\**" />
	</ItemGroup>
</Project>
